# Generated by Django 2.2.4 on 2020-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_X', '0005_auto_20201117_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followed',
        ),
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(related_name='_profile_follow_+', to='app_X.Profile'),
        ),
    ]
