# Generated by Django 2.2.4 on 2020-11-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_X', '0008_auto_20201117_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='who_follows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='you_followed',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='_profile_followers_+', to='app_X.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', to='app_X.Profile'),
        ),
    ]
