# Generated by Django 2.2.4 on 2020-11-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_X', '0011_auto_20201118_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='New Comer', max_length=30),
        ),
    ]
