# Generated by Django 2.2.4 on 2020-11-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_X', '0004_auto_20201117_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(related_name='_profile_follower_+', to='app_X.Profile'),
        ),
    ]
