# Generated by Django 2.2.4 on 2020-11-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_X', '0013_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
