# Generated by Django 2.2.4 on 2020-11-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_X', '0002_auto_20201117_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(related_name='followers', to='app_LR.User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='app_LR.User'),
        ),
    ]
